export enum QueryType {
  TOKEN = "TOKEN",
  A_TOKEN = "A_TOKEN",
  VAULT_TOKEN = "VAULT_TOKEN",
  PAIR = "PAIR",
  ASSET_PRICES = "ASSET_PRICES",
  VAULT = "VAULT",
  LENDING_POOL = "LENDING_POOL",
  POSITIONS = "POSITIONS",
  HISTORY = "HISTORY",
  PUBLIC_SALE_DATA = "PUBLIC_SALE_DATA",
  LOCK_DATA = "LOCK_DATA",
  AIRDROP_DATA = "AIRDROP_DATA",
}
