export enum QueryType {
  TOKEN = "TOKEN",
  VAULT_TOKEN = "VAULT_TOKEN",
  PAIR = "PAIR",
  PAIR_PRICES = "PAIR_PRICES",
  OPTION_BORROW_RATES = "OPTION_BORROW_RATES",
  ASSET_PRICES = "ASSET_PRICES",
  VAULT = "VAULT",
  POSITIONS = "POSITIONS",
  HISTORY = "HISTORY",
  PUBLIC_SALE_DATA = "PUBLIC_SALE_DATA",
  LOCK_DATA = "LOCK_DATA",
  AIRDROP_DATA = "AIRDROP_DATA",
}
